#include "or_head_marker.h"

#include "or_config.h"
#include "or_log.h"

#include "tefkernel/patchlib/field.h"
#include "tefkernel/patchlib/method.h"
#include "tefkernel/patchlib/type.h"
#include "tefkernel/terraria/texture2d.h"

#include <math.h>
#include <stdint.h>
#include <string.h>

#define OR_FX_TILE_SIZE 128
#define OR_FX_SHEET_WIDTH (OR_FX_TILE_SIZE * 3)
#define OR_LOG(level, ...) do { or_log_write((level), __VA_ARGS__); } while (0)

/* These layouts are taken from the supplied Terraria 1.4.5.8 IL2CPP source:
 * Vector2={float X,Y}, Rectangle={int X,Y,Width,Height}, and Color's native
 * byte order is A,B,G,R.  Calling EntitySpriteDraw through its verified
 * Android method pointer avoids the optional struct-value bridge that the
 * user's installed TEFKernel does not export. */
struct OR_MarkerVector2 { float x; float y; };
struct OR_MarkerRectangle { int32_t x; int32_t y; int32_t width; int32_t height; };
struct OR_MarkerColor { uint8_t a; uint8_t b; uint8_t g; uint8_t r; };

typedef struct OR_HeadMarkerState {
    patch_handle_t draw_npc_method;
    patch_handle_t draw_npc_method_lit;
    patch_handle_t frame_method;
    patch_handle_t screen_position_method;
    patch_handle_t player_dead_field;
    patch_handle_t entity_sprite_draw_method;
    void (*entity_sprite_draw)(patch_handle_t texture,
                               struct OR_MarkerVector2 position,
                               struct OR_MarkerRectangle source_rect,
                               struct OR_MarkerColor color,
                               float rotation,
                               struct OR_MarkerVector2 origin,
                               float scale,
                               int32_t effects,
                               float layer_depth);
    struct OR_MarkerVector2 (*get_screen_position)(void);
    patch_handle_t texture;
    bool ready;
    uint8_t create_attempts;
    uint32_t draw_logs;
} OR_HeadMarkerState;

static OR_HeadMarkerState g_marker;

/* The three supplied effects are packed into one RGBA atlas. No PNG decoder
 * is needed at runtime; the generated byte array is uploaded once. */
#include "assets/foot_fx_atlas.inc"

static bool ensure_texture(void) {
#if !defined(__ANDROID__)
    return false;
#else
    if (g_marker.texture && patchlib_is_valid && patchlib_is_valid(g_marker.texture)) return true;
    if (!terraria_texture2d_create || !patchlib_is_valid) return false;
    if (g_marker.create_attempts >= 3u) return false;
    ++g_marker.create_attempts;
    g_marker.texture = terraria_texture2d_create(
        OR_FX_SHEET_WIDTH, OR_FX_TILE_SIZE, TEXTURE_FORMAT_RGBA32,
        (void *)foot_fx_atlas_rgba, foot_fx_atlas_rgba_len);
    if (!g_marker.texture || !patchlib_is_valid(g_marker.texture)) {
        OR_LOG(MOD_LOG_LEVEL_WARNING,
               "[FOOT_FX_TEXTURE] created=no attempt=%u reason=texture_create_failed",
               (unsigned)g_marker.create_attempts);
        g_marker.texture = PATCH_NULL;
        return false;
    }
    OR_LOG(MOD_LOG_LEVEL_INFO,
           "[FOOT_FX_TEXTURE] created=yes size=%dx%d mode=pixel_art_atlas_rgba32",
           OR_FX_SHEET_WIDTH, OR_FX_TILE_SIZE);
    return true;
#endif
}

bool or_head_marker_probe(const OR_Runtime *runtime) {
#if !defined(__ANDROID__)
    (void)runtime;
    OR_LOG(MOD_LOG_LEVEL_INFO,
           "[FOOT_FX_PROBE] ready=no reason=android_arm64_only");
    return false;
#else
    patch_handle_t main_type;
    patch_handle_t sprite_batch_type;
    patch_handle_t npc_type;
    patch_handle_t player_type;
    patch_handle_t texture_type;
    patch_handle_t vector2_type;
    patch_handle_t rectangle_type;
    patch_handle_t color_type;
    patch_handle_t sprite_effects_type;
    patch_handle_t bool_type;
    patch_handle_t float_type;
    patch_handle_t draw_npc_args[4];
    patch_handle_t draw_npc_lit_args[6];
    patch_handle_t entity_draw_args[9];
    patch_handle_t light_map_type;

    memset(&g_marker, 0, sizeof(g_marker));
    if (!runtime || !runtime->field_position_probe || !runtime->field_width ||
        !runtime->field_height || !runtime->position_vector2_metadata_ready ||
        !patchlib_type_get_type || !patchlib_type_get_method_by_param_types ||
        !patchlib_get_basic_type || !patchlib_method_get_pointer ||
        !terraria_texture2d_create) {
        OR_LOG(MOD_LOG_LEVEL_INFO,
               "[FOOT_FX_PROBE] ready=no reason=runtime_or_direct_pointer_unavailable "
               "pointerApi=%s textureApi=%s",
               patchlib_method_get_pointer ? "yes" : "no",
               terraria_texture2d_create ? "yes" : "no");
        return false;
    }

    main_type = patchlib_type_get_type("Terraria", "Main");
    sprite_batch_type = patchlib_type_get_type("Microsoft.Xna.Framework.Graphics", "SpriteBatch");
    npc_type = patchlib_type_get_type("Terraria", "NPC");
    player_type = patchlib_type_get_type("Terraria", "Player");
    texture_type = patchlib_type_get_type("Microsoft.Xna.Framework.Graphics", "Texture2D");
    vector2_type = patchlib_type_get_type("Microsoft.Xna.Framework", "Vector2");
    rectangle_type = patchlib_type_get_type("Microsoft.Xna.Framework", "Rectangle");
    color_type = patchlib_type_get_type("Microsoft.Xna.Framework.Graphics", "Color");
    sprite_effects_type = patchlib_type_get_type("Microsoft.Xna.Framework.Graphics", "SpriteEffects");
    light_map_type = patchlib_type_get_type("Terraria", "Lighting+LightMap");
    if (!light_map_type) light_map_type = patchlib_type_get_type("Terraria", "LightMap");
    bool_type = patchlib_get_basic_type(PATCH_BOOL);
    float_type = patchlib_get_basic_type(PATCH_FLOAT);
    if (!main_type || !sprite_batch_type || !npc_type || !texture_type || !vector2_type ||
        !rectangle_type || !color_type || !sprite_effects_type || !bool_type || !float_type) {
        OR_LOG(MOD_LOG_LEVEL_INFO,
               "[FOOT_FX_PROBE] ready=no reason=required_type_unavailable");
        return false;
    }

    draw_npc_args[0] = sprite_batch_type;
    draw_npc_args[1] = npc_type;
    draw_npc_args[2] = bool_type;
    draw_npc_args[3] = vector2_type;
    entity_draw_args[0] = texture_type;
    entity_draw_args[1] = vector2_type;
    entity_draw_args[2] = rectangle_type;
    entity_draw_args[3] = color_type;
    entity_draw_args[4] = float_type;
    entity_draw_args[5] = vector2_type;
    entity_draw_args[6] = float_type;
    entity_draw_args[7] = sprite_effects_type;
    entity_draw_args[8] = float_type;
    draw_npc_lit_args[0] = sprite_batch_type;
    draw_npc_lit_args[1] = npc_type;
    draw_npc_lit_args[2] = bool_type;
    draw_npc_lit_args[3] = vector2_type;
    draw_npc_lit_args[4] = light_map_type;
    draw_npc_lit_args[5] = rectangle_type;

    g_marker.draw_npc_method = patchlib_type_get_method_by_param_types(
        main_type, "DrawNPCDirect", 4, draw_npc_args);
    if (light_map_type) {
        g_marker.draw_npc_method_lit = patchlib_type_get_method_by_param_types(
            main_type, "DrawNPCDirect", 6, draw_npc_lit_args);
    }
    {
        patch_handle_t frame_args[1];
        frame_args[0] = bool_type;
        g_marker.frame_method = patchlib_type_get_method_by_param_types(
            main_type, "DrawNPCs", 1, frame_args);
    }
    g_marker.screen_position_method = patchlib_type_get_method_by_param_types(
        main_type, "get_screenPosition", 0, NULL);
    if (player_type && patchlib_type_get_field)
        g_marker.player_dead_field = patchlib_type_get_field(player_type, "dead");
    if (g_marker.screen_position_method) {
        g_marker.get_screen_position = (struct OR_MarkerVector2 (*)(void))
            patchlib_method_get_pointer(g_marker.screen_position_method);
    }
    g_marker.entity_sprite_draw_method = patchlib_type_get_method_by_param_types(
        main_type, "EntitySpriteDraw", 9, entity_draw_args);
    if (g_marker.entity_sprite_draw_method) {
        g_marker.entity_sprite_draw = (void (*)(patch_handle_t,
                                                  struct OR_MarkerVector2,
                                                  struct OR_MarkerRectangle,
                                                  struct OR_MarkerColor,
                                                  float,
                                                  struct OR_MarkerVector2,
                                                  float,
                                                  int32_t,
                                                  float))patchlib_method_get_pointer(
            g_marker.entity_sprite_draw_method);
    }
    g_marker.ready = g_marker.frame_method && g_marker.entity_sprite_draw_method &&
                     g_marker.entity_sprite_draw && g_marker.get_screen_position &&
                     g_marker.player_dead_field;
    OR_LOG(MOD_LOG_LEVEL_INFO,
           "[FOOT_FX_PROBE] ready=%s frame=Main.DrawNPCs(1):%s hook4=%s hook6=%s "
           "screenPositionGetter=%s playerDeadField=%s draw=Main.EntitySpriteDraw(9) "
           "textureApi=%s drawCall=direct_method_pointer",
           g_marker.ready ? "yes" : "no",
           g_marker.frame_method ? "yes" : "no",
           g_marker.draw_npc_method ? "yes" : "no",
           g_marker.draw_npc_method_lit ? "yes" : "no",
           g_marker.get_screen_position ? "yes" : "no",
           g_marker.player_dead_field ? "yes" : "no",
           terraria_texture2d_create ? "yes" : "no");
    return g_marker.ready;
#endif
}

patch_handle_t or_head_marker_draw_method(void) {
    return g_marker.ready ? g_marker.draw_npc_method : PATCH_NULL;
}

patch_handle_t or_head_marker_draw_method_lit(void) {
    return g_marker.ready ? g_marker.draw_npc_method_lit : PATCH_NULL;
}

patch_handle_t or_head_marker_frame_method(void) {
    return g_marker.ready ? g_marker.frame_method : PATCH_NULL;
}

bool or_head_marker_get_screen_position(float out[2]) {
    struct OR_MarkerVector2 p;
    if (!out || !g_marker.ready || !g_marker.get_screen_position) return false;
    p = g_marker.get_screen_position();
    if (!isfinite(p.x) || !isfinite(p.y)) return false;
    out[0] = p.x; out[1] = p.y;
    return true;
}

bool or_head_marker_read_player_dead(patch_handle_t player, bool *dead_out) {
#if !defined(__ANDROID__)
    (void)player; (void)dead_out;
    return false;
#else
    uint8_t dead = 1u;
    if (!player || !dead_out || !g_marker.player_dead_field || !patchlib_field_get_value) return false;
    patchlib_field_get_value(g_marker.player_dead_field, player, &dead);
    *dead_out = dead != 0u;
    return true;
#endif
}

void or_head_marker_draw(const OR_Runtime *runtime,
                         patch_handle_t npc,
                         OR_EliteTier tier,
                         const float screen_pos[2]) {
#if !defined(__ANDROID__)
    (void)runtime;
    (void)npc;
    (void)tier;
    (void)screen_pos;
#else
    uint8_t position_raw[8] = {0};
    float position[2];
    struct OR_MarkerVector2 draw_position;
    int32_t width = 0;
    int32_t height = 0;
    struct OR_MarkerRectangle source_rect = {
        (int32_t)((tier - OR_TIER_ALTERED) * OR_FX_TILE_SIZE), 0,
        OR_FX_TILE_SIZE, OR_FX_TILE_SIZE
    };
    struct OR_MarkerColor color;
    float rotation = 0.0f;
    struct OR_MarkerVector2 origin = {64.0f, 116.0f};
    /* Keep the aura compact and place its lowest pixels just below the feet. */
    float scale = 0.35f;
    int32_t effects = 0;
    float layer_depth = 0.0f;

    if (!g_marker.ready || !runtime || !npc || !screen_pos ||
        tier <= OR_TIER_NONE || tier >= OR_TIER_COUNT ||
        !runtime->field_position_probe || !runtime->field_width ||
        !runtime->field_height || !patchlib_field_get_value ||
        !g_marker.entity_sprite_draw || !ensure_texture()) return;

    patchlib_field_get_value(runtime->field_position_probe, npc, position_raw);
    memcpy(position, position_raw, sizeof(position));
    patchlib_field_get_value(runtime->field_width, npc, &width);
    patchlib_field_get_value(runtime->field_height, npc, &height);
    if (!isfinite(position[0]) || !isfinite(position[1]) ||
        !isfinite(screen_pos[0]) || !isfinite(screen_pos[1]) ||
        width < 1 || width > 2048 || height < 1 || height > 2048) return;

    draw_position.x = position[0] + (float)width * 0.5f - screen_pos[0];
    draw_position.y = position[1] + (float)height + 8.0f - screen_pos[1];
    /* Preserve the colours and soft glows from the supplied artwork. */
    color.a = 255u; color.b = 255u; color.g = 255u; color.r = 255u;
    g_marker.entity_sprite_draw(g_marker.texture, draw_position, source_rect,
                                color, rotation, origin, scale, effects,
                                layer_depth);
    if (g_marker.draw_logs < 12u) {
        ++g_marker.draw_logs;
        OR_LOG(MOD_LOG_LEVEL_INFO,
               "[FOOT_FX_DRAW] result=drawn tier=%s x=%.1f y=%.1f scale=%.2f",
               or_elite_tier_name(tier), (double)draw_position.x,
               (double)draw_position.y, (double)scale);
    }
#endif
}

void or_head_marker_reset(void) {
    memset(&g_marker, 0, sizeof(g_marker));
}
